USE Kahoot;
GO

ALTER TABLE Role NOCHECK CONSTRAINT ALL;
ALTER TABLE [User] NOCHECK CONSTRAINT ALL;
ALTER TABLE Quiz NOCHECK CONSTRAINT ALL;
ALTER TABLE Question NOCHECK CONSTRAINT ALL;
ALTER TABLE Answer NOCHECK CONSTRAINT ALL;
ALTER TABLE [Session] NOCHECK CONSTRAINT ALL;
ALTER TABLE QuestionSession NOCHECK CONSTRAINT ALL;
ALTER TABLE Team NOCHECK CONSTRAINT ALL;
ALTER TABLE Player NOCHECK CONSTRAINT ALL;
ALTER TABLE PlayerAnswer NOCHECK CONSTRAINT ALL;
GO

DELETE FROM PlayerAnswer;
DELETE FROM Player;
DELETE FROM QuestionSession;
DELETE FROM Team;
DELETE FROM [Session];
DELETE FROM Answer;
DELETE FROM Question;
DELETE FROM Quiz;
DELETE FROM [User];
DELETE FROM Role;

INSERT INTO Role (RoleID, RoleName) VALUES
(1, 'Admin'),
(2, 'User'),
(3, 'Teacher');

SET IDENTITY_INSERT [dbo].[User] ON;
GO

INSERT [dbo].[User] ([UserID], [FullName], [Email], [Password], [Age], [Avatar], [fcmToken], [Status], [RoleID]) VALUES 
(1, N'New User', N'user@example.com', N'AQAAAAIAAYagAAAAEJC6r2LMSMDB1nSfXeYadVFihZL+PHOrpKK4g6s0kDy9LRR4sYRlbYbjDh3pF95RZg==', 21, N'', NULL, N'Active', 2),
(2, N'Admin', N'admin@example.com', N'AQAAAAIAAYagAAAAEJC6r2LMSMDB1nSfXeYadVFihZL+PHOrpKK4g6s0kDy9LRR4sYRlbYbjDh3pF95RZg==', 30, N'', NULL, N'Active', 1),
(3, N'Teacher', N'teacher@example.com', N'AQAAAAIAAYagAAAAEJC6r2LMSMDB1nSfXeYadVFihZL+PHOrpKK4g6s0kDy9LRR4sYRlbYbjDh3pF95RZg==', 20, N'', NULL, N'Active', 3),
GO
